; SIP Trunk to Tele2 KZ (almpbx.tele2.kz)

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[tele2-endpoint]
type=endpoint
context=outbound
disallow=all
allow=alaw
allow=ulaw
aors=tele2-aor
auth=tele2-auth
direct_media=no
dtmf_mode=rfc4733
from_user=77003860130

[tele2-auth]
type=auth
auth_type=userpass
username=bIBZ29zN
password=n0Ojyji3

[tele2-aor]
type=aor
default_expiration=120

[tele2-reg]
type=registration
outbound_auth=tele2-auth
server_uri=sip:almpbx.tele2.kz:5060
client_uri=sip:77003860130@almpbx.tele2.kz:5060
retry_interval=60
expiration=120
