; SIP Trunk to Tele2 KZ (almpbx.tele2.kz)

[tele2-endpoint]
type=endpoint
context=outbound
disallow=all
allow=alaw
allow=ulaw
aors=tele2-aor
auth=tele2-auth
direct_media=no
dtmf_mode=rfc4733
from_user=bIBZ29zN
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes

[tele2-auth]
type=auth
auth_type=userpass
username=bIBZ29zN
password=n0Ojyji3

[tele2-aor]
type=aor
max_retries=3
remove_existing=yes
default_expiration=120
minimum_expiration=120
maximum_expiration=3600

[tele2-registration]
type=registration
outbound_auth=tele2-auth
server_uri=sip:almpbx.tele2.kz:5060
client_uri=sip:bIBZ29zN@almpbx.tele2.kz:5060
retry_interval=60
expiration=120
