[media_connection_pipecat]
type = websocket_client
uri = ws://pipecat_agent:8082/ws/media
protocols = media
username = mediauser
password = mediapass
connection_type = per_call_config
connection_timeout = 10000
reconnect_interval = 1000
reconnect_attempts = 5
tls_enabled = no
